// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	Args
	Result
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Args struct {
	Arg1 int64 `protobuf:"varint,1,opt,name=arg1" json:"arg1,omitempty"`
	Arg2 int64 `protobuf:"varint,2,opt,name=arg2" json:"arg2,omitempty"`
}

func (m *Args) Reset()                    { *m = Args{} }
func (m *Args) String() string            { return proto.CompactTextString(m) }
func (*Args) ProtoMessage()               {}
func (*Args) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Args) GetArg1() int64 {
	if m != nil {
		return m.Arg1
	}
	return 0
}

func (m *Args) GetArg2() int64 {
	if m != nil {
		return m.Arg2
	}
	return 0
}

type Result struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Result) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Args)(nil), "api.args")
	proto.RegisterType((*Result)(nil), "api.result")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Calc service

type CalcClient interface {
	Sum(ctx context.Context, in *Args, opts ...grpc.CallOption) (*Result, error)
	Sub(ctx context.Context, in *Args, opts ...grpc.CallOption) (*Result, error)
	Mul(ctx context.Context, in *Args, opts ...grpc.CallOption) (*Result, error)
	Div(ctx context.Context, in *Args, opts ...grpc.CallOption) (*Result, error)
}

type calcClient struct {
	cc *grpc.ClientConn
}

func NewCalcClient(cc *grpc.ClientConn) CalcClient {
	return &calcClient{cc}
}

func (c *calcClient) Sum(ctx context.Context, in *Args, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.Calc/sum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Sub(ctx context.Context, in *Args, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.Calc/sub", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Mul(ctx context.Context, in *Args, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.Calc/mul", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Div(ctx context.Context, in *Args, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/api.Calc/div", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Calc service

type CalcServer interface {
	Sum(context.Context, *Args) (*Result, error)
	Sub(context.Context, *Args) (*Result, error)
	Mul(context.Context, *Args) (*Result, error)
	Div(context.Context, *Args) (*Result, error)
}

func RegisterCalcServer(s *grpc.Server, srv CalcServer) {
	s.RegisterService(&_Calc_serviceDesc, srv)
}

func _Calc_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Args)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Calc/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Sum(ctx, req.(*Args))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calc_Sub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Args)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Sub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Calc/Sub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Sub(ctx, req.(*Args))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calc_Mul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Args)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Mul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Calc/Mul",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Mul(ctx, req.(*Args))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calc_Div_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Args)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalcServer).Div(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Calc/Div",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalcServer).Div(ctx, req.(*Args))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Calc",
	HandlerType: (*CalcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sum",
			Handler:    _Calc_Sum_Handler,
		},
		{
			MethodName: "sub",
			Handler:    _Calc_Sub_Handler,
		},
		{
			MethodName: "mul",
			Handler:    _Calc_Mul_Handler,
		},
		{
			MethodName: "div",
			Handler:    _Calc_Div_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xd2, 0xe3, 0x62, 0x49, 0x2c,
	0x4a, 0x2f, 0x16, 0x12, 0x02, 0xd3, 0x86, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x60, 0x36,
	0x54, 0xcc, 0x48, 0x82, 0x09, 0x2e, 0x66, 0xa4, 0x24, 0xc7, 0xc5, 0x56, 0x94, 0x5a, 0x5c, 0x9a,
	0x53, 0x22, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x0a, 0xd5, 0x02, 0xe1, 0x18, 0x75,
	0x31, 0x72, 0xb1, 0x38, 0x27, 0xe6, 0x24, 0x0b, 0xc9, 0x73, 0x31, 0x17, 0x97, 0xe6, 0x0a, 0x71,
	0xea, 0x81, 0x2c, 0x04, 0x59, 0x21, 0xc5, 0x0d, 0x66, 0x42, 0x74, 0x2b, 0x31, 0x40, 0x14, 0x24,
	0xe1, 0x57, 0x90, 0x5b, 0x9a, 0x83, 0x5f, 0x41, 0x4a, 0x66, 0x19, 0x6e, 0x05, 0x49, 0x6c, 0x60,
	0x8f, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x2b, 0xd0, 0x5d, 0xf5, 0x00, 0x00, 0x00,
}
